language: php

dist: trusty

php:
  - '7.3'
  
before_script:
  - composer install --no-interaction
  - cp .env.testing .env
  - touch database.sqlite
  - php artisan migrate:refresh --seed --no-interaction
  
script:
  - vendor/bin/phpcs --config-set show_warnings 0
  - vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=*/routes/*,*/migrations/*,*/tests/* app
  - vendor/bin/phpunit --coverage-text --testdox