language: php

php:
  - '7.3'

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required
  
before_script:
  - composer install --no-interaction
  - mysql -e 'create database test;'
  - cp .env.testing .env
  - php artisan migrate:refresh --seed --no-interaction
  
script:
  - vendor/bin/phpcs --config-set show_warnings 0
  - vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=*/routes/*,*/migrations/*,*/tests/* app
  - vendor/bin/phpunit --coverage-text --testdox